name: Test Python hello world
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  python-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: run file
        run: python hello.py
