name: Run test workflow
  on:
    push:
      branches: "*"
    pull_request:
      branches: "*"
jobs: 
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest